version: "3.8"

services:
  nginx:
    image: nginx
    volumes:
      - .docker/nginx/templates/*.template:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80

  web:
    build:
      context: .
    volumes:
      - .:/usr/app
    ports:
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    env_file: .env
    networks:
      pancakelock-api:
    depends_on:
      - test_db

  test_db:
    image: postgres
    container_name: db
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      pancakelock-api:

networks:
  pancakelock-api:
