version: "3.8"

services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/app
    ports:
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    networks:
      pancakelock-api:

networks:
  pancakelock-api:

#==5.24.0