version: "3.8"

services:
#  nginx:
#    image: nginx
##    context:
#    volumes:
#      - .docker/nginx/templates/*.template:/etc/nginx/templates
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=127.0.0.1
#      - NGINX_PORT=80

  web:
    build:
      context: .
    volumes:
      - .:/usr/app
    ports:
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    env_file: .env
    networks:
      bebras:
    depends_on:
      - postgres

  postgres:
#    build:
#      context: ./postgres
#      dockerfile: Dockerfile
    image: postgres
    container_name: postgres
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
#      - ./postgres/init.sql:/docker-enterypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    #    network_mode: "host"
    networks:
      bebras:

networks:
  bebras:
