name: build action

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
        - name: Check Out Repo
          uses: actions/checkout@v2

        - name: Docker Login
          uses: docker/login-action@v1.10.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo_shit_project:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

        - name: Deploy to Docker server
          uses: wshihadeh/docker-deployment-action@v1
          with:
            remote_docker_host: root@161.35.63.104 -p 228
            remote_docker_port: 228
            ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
            ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            deployment_mode: docker-compose
            copy_stack_file: true
            deploy_path: /root/demoCICD
            stack_file_name: docker-compose.yaml
            keep_files: 5
#            args: my_applicaion